{% set python_min = "3.10" %}
{% set name = "txl-kernel" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_kernel-{{ version }}.tar.gz
  sha256: e1e4d0e127ee711129198e8096fd32a5d8936d69a467096619a14e83818c3d00

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl >=0.2.18,<0.3.0
    - asphalt >=4.0.0,<5.0.0
    - python-dateutil >=2.8.2
    - pycrdt >=0.10.9,<0.11.0

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl_kernel

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/kernel
  summary: TXL plugin for a kernel driver
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/kernel
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
